In [3]:
import pandas as pd
import pickle
import sqlite3

In [5]:
pd.read_pickle('df_nashdomrf.pkl')

,id,hobjId,pdId,region,address,floorMin,floorMax,objElemLivingCnt,objReady100PercDt,wallMaterialShortDesc,...,metro.time,metro.isWalk,metro.colors,complexShortNm,airQualityIndexValue,greenAreaIndexValue,developer.bankruptStage.bankruptStageCd,developer.bankruptStage.bankruptStageDesc,developer.bankruptStage.bankruptLawUrl,developer.orgBankruptMsgDttm
0,13399,34754,28141,72,"г Тюмень, ул Профсоюзная, д. 56",1,1,0,2024-12-31,Другое,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13397,37201,28141,72,"г Тюмень, ул Профсоюзная, д. 56",6,12,65,2024-12-31,Другое,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13383,39024,28105,72,"г Тюмень, ул Профсоюзная, д. 56",4,20,68,2023-12-31,Другое,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13398,37165,28141,72,"г Тюмень, ул Профсоюзная, д. 56",7,10,43,2024-12-31,Другое,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13391,37219,28101,72,"г Тюмень, ул Профсоюзная, д. 56",3,12,44,2023-12-31,Другое,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11709,56129,136843,794938,32,поселок Свень,9,9,103,2026-06-30,Монолит-кирпич,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11710,56132,136846,794938,32,поселок Свень,9,9,103,2030-12-31,Монолит-кирпич,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11711,56131,136845,794938,32,поселок Свень,9,9,103,2029-06-30,Монолит-кирпич,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11712,56130,136844,794938,32,поселок Свень,9,9,110,2027-12-31,Монолит-кирпич,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11713,51137,131791,582963,32,"г Брянск, район Советский р-н, ул Степная, д. ...",7,9,104,2024-09-30,Монолит-кирпич,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
unpickled_df_nashdomrf = pd.read_pickle('df_nashdomrf.pkl')
#print(unpickled_df_nashdomrf)

In [11]:
unpickled_df_nashdomrf.to_csv('./new_df_nashdomrf.csv')

In [13]:
unpickled_df_nashdomrf.to_pickle("./new_df_nashdomrf.pkl")

In [15]:
conn = sqlite3.connect('test_database')
unpickled_df_nashdomrf.to_sql('nashdomrf', conn, if_exists='replace', index = False)
conn.commit()
conn.close()

ProgrammingError: Error binding parameter 24: type 'list' is not supported